### ISSUE TITLE
Undefined simplexml_load_string() function when searching for paper without existing summary

### ISSUE THREAD

**Issue by decodyng** [ShortScience-org/shortscience.org#23]
When trying to add a new summary on a paper not currently present on the site, the site navigates to the url https://shortscience.org/search?term=<term>, and gets the following error: 

```
Details
Type: Error
Message: Call to undefined function simplexml_load_string()
File: /home/shortscience/public_html/functions.php
Line: 358
Trace
#0 /home/shortscience/public_html/functions.php(92): searchBibsonomy()
#1 /home/shortscience/public_html/index.php(108): performSearch()
#2 [internal function]: Closure->{closure}()
#3 /home/shortscience/public_html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func()
#4 /home/shortscience/public_html/vendor/slim/slim/Slim/Route.php(325): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /home/shortscience/public_html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\Route->__invoke()
#6 /home/shortscience/public_html/vendor/slim/slim/Slim/Route.php(297): Slim\Route->callMiddlewareStack()
#7 /home/shortscience/public_html/vendor/slim/slim/Slim/App.php(441): Slim\Route->run()
#8 /home/shortscience/public_html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\App->__invoke()
#9 /home/shortscience/public_html/vendor/slim/slim/Slim/App.php(337): Slim\App->callMiddlewareStack()
#10 /home/shortscience/public_html/vendor/slim/slim/Slim/App.php(298): Slim\App->process()
#11 /home/shortscience/public_html/index.php(762): Slim\App->run()
#12 {main}
```

It seems like maybe something changed in one of your imported libraries such that this function is no longer appropriately being defined?

**Comment by ieee8023** [comment]
Should be fixed now. Sorry about that! It was indeed missing a library after a package update.
